import '../styles/globals.css'
import 'mapbox-gl/dist/mapbox-gl.css'
import { UberProvider } from '../context/uberContext'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <UberProvider>
      <Head>
        <title>UBER - BLOCKCHAIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Component {...pageProps} />
    </UberProvider>
  )
}

export default MyApp